logging.config=classpath:logback-spring.xml
spring.application.name=corenotificacion-api
spring.profiles.active=prod
spring.config.import=optional:configserver:http://adminUniConfig:U%23niSi%24m0n_2026%40Prod@localhost:8888
cors.allowed-origins=https://portal.unisimon.edu.co,https://auth.unisimon.edu.co

# Management - Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

# Micrometer Tracing
management.tracing.sampling.probability=0.1

app.file-service.url=http://192.168.3.83/file
app.file-service.token=eyJhbGciOiJIUzUxMiJ9.eyJzZXNzaW9uSWQiOiJlZWRkNjdlYS00NTdiLTRkNWItODFlZC0zZTI0ZTg3OWJiNGIiLCJzdWIiOiJ1c2VyZnRwIiwiaWF0IjoxNzc3MDQ0NjUzfQ.NS7Ttai6iXBufWSbzUPXLhYivuW7-kx-DtFrFm2577O2rKM8uJAaYmoMHWxv8-Sqt0tGXuQLs-csKJRiVtIdzA
mailer.url=https://pagoscuc.unisimon.edu.co/receiver/enviar
