spring.application.name=corenotificacion-api
spring.profiles.active=dev
server.port=8095
spring.main.allow-bean-definition-overriding=true
sentry.dsn=http://a4cded9f5e83448fabe8f30ed4b341f9@192.168.3.83:8000/2
spring.config.import=optional:configserver:http://configUser:ConfigPass123!@192.168.3.83:8888/config

OTEL_SERVICE_NAME=corenotificacion-api
server.servlet.context-path=/corenotificacion
logging.config=classpath:logback-spring.xml
cors.allowed-origins=http://localhost:3001,http://localhost:3000

# Servicios Externos
app.file-service.url=http://192.168.3.83/file
app.file-service.token=eyJhbGciOiJIUzUxMiJ9.eyJzZXNzaW9uSWQiOiJlZWRkNjdlYS00NTdiLTRkNWItODFlZC0zZTI0ZTg3OWJiNGIiLCJzdWIiOiJ1c2VyZnRwIiwiaWF0IjoxNzc3MDQ0NjUzfQ.NS7Ttai6iXBufWSbzUPXLhYivuW7-kx-DtFrFm2577O2rKM8uJAaYmoMHWxv8-Sqt0tGXuQLs-csKJRiVtIdzA
mailer.url=https://pagoscuc.unisimon.edu.co/receiver/enviar

# Swagger Security
swagger.security.username=unisimon
swagger.security.password=$2a$12$.uwK2zJ3QCoImiepWzRtSOH5R1CT0VGEXV3usyH6P.y8uSl.P9LMm

# SpringDoc Properties
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha

# RabbitMQ STOMP Broker Relay Config
spring.rabbitmq.host=192.168.3.87
spring.rabbitmq.port=5672
spring.rabbitmq.username=u1s2r3
spring.rabbitmq.password=U1n2i3s4i5m6o7n2026#

# Configuración del STOMP Relay
spring.websocket.stomp.relay.host=192.168.3.87
spring.websocket.stomp.relay.port=61613
spring.websocket.stomp.relay.system-login=u1s2r3
spring.websocket.stomp.relay.system-passcode=U1n2i3s4i5m6o7n2026#
spring.websocket.stomp.relay.client-login=u1s2r3
spring.websocket.stomp.relay.client-passcode=U1n2i3s4i5m6o7n2026#