spring.application.name=corenotificacion-api
spring.profiles.active=dev
spring.main.allow-bean-definition-overriding=true
sentry.dsn=http://a4cded9f5e83448fabe8f30ed4b341f9@192.168.3.83:8000/2
spring.config.import=optional:configserver:http://adminUniConfig:U%23niSi%24m0n_2026%40Prod@10.0.30.170/config